# OS specific
sudo: false
dist: trusty
python: '3.6'
language: node_js
node_js:
  - 'lts/dubnium'
cache: yarn


branches:
  only:
  - master
  - development


before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install -U pip
  - pip install awscli
  - pip install sam-cli
  - aws --version
  - sam --version

install:
  - yarn
  - lerna bootstrap

script:
  - yarn build
  - yarn validate
  - yarn package

after_success:
  - echo "Build success"
after_failure:
  - echo "Build failed"

deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: master


