sudo: false
language: node_js
os: osx

addons:
  homebrew:
    update: true
    packages: 
      - awscli
    taps: aws/tap

node_js:
  - 'lts/dubnium'


cache:
  directories:
    - $HOME/Library/Caches/Homebrew
  yarn: true

env:
  - S3_DEPLOY_BUCKET="c1-serverless-app-deploy"

branches:
  only:
  - development


before_install:
  - brew install awscli
  - brew install aws-sam-cli

install:
  - yarn install
  - lerna bootstrap

script:
  - yarn build
  - yarn package

deploy:
  - provider: script
    script:
      - yarn deploy
      - yarn sync
    on:
      branch: development


