# OS specific
sudo: false
dist: trusty
python: '3.6.1'
addons:
  apt:
    packages:
      - python3
      - 'python3-pip'
language: node_js
node_js:
  - 'lts/dubnium'
cache: yarn


branches:
  only:
  - master
  - development


before_install:
  - pip3 install awscli
  - pip3 install aws-sam-cli
  - aws --version
  - sam --version

install:
  - yarn
  - lerna bootstrap

script:
  - yarn build
  - yarn validate
  - yarn package

after_success:
  - echo "Build success"
after_failure:
  - echo "Build failed"

deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: master


