# OS specific
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - awscli
language: node_js
node_js:
  - 'lts/dubnium'
cache: yarn


branches:
  only:
  - master
  - development


before_install:
  - git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew tap aws/tap
  - brew install aws-sam-cli
  - aws --version
  - sam --version

install:
  - yarn
  - lerna bootstrap

script:
  - yarn build
  - yarn validate
  - yarn package

after_success:
  - echo "Build success"
after_failure:
  - echo "Build failed"

# deploy:
#   - provider: script
#     script: yarn deploy
#     on:
#       branch: master


