sudo: false
dist: xenial

addons:
  apt:
    install:
      - python3
      - pip3



language: node_js
node_js:
  - 'lts/dubnium'


cache:
  yarn: true
  pip: true
  apt: true

env:
  - S3_DEPLOY_BUCKET="c1-serverless-app-deploy"

branches:
  only:
  - master
  - development


before_install:
  - pip3 install --user aws-cli
  - pip3 install --user aws-sam-cli

install:
  - yarn install
  - lerna bootstrap

script:
  - yarn build
  - yarn package

deploy:
  - provider: script
    script:
      - yarn deploy
      - yarn sync
    on:
      branch: development


