# OS specific
sudo: false
dist: trusty
python: '2.7'
addons:
  apt:
    packages:
      - aws-cli
language: node_js
node_js:
  - 'lts/dubnium'
cache: yarn


branches:
  only:
  - master
  - development


before_install:
#   - pip install awscli --user
#   - pip install aws-sam-cli --user
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - brew tap aws/tap
  - brew install aws-sam-cli
  - aws --version
  - sam --version

# install:
#   - yarn
#   - lerna bootstrap

# script:
#   - yarn build
#   - yarn validate
#   - yarn package

# after_success:
#   - echo "Build success"
# after_failure:
#   - echo "Build failed"

# deploy:
#   - provider: script
#     script: yarn deploy
#     on:
#       branch: master


