sudo: false
dist: trusty
python: "3.6"
cache:
  yarn: true
  pip: true

language: node_js
node_js:
  - 'lts/dubnium'

env:
  - S3_DEPLOY_BUCKET="c1-serverless-app-deploy"

branches:
  only:
  - master
  - development


before_install:
  - pip install --user aws-cli
  - pip install --user aws-sam-cli

install:
  - yarn install
  - lerna bootstrap

script:
  - yarn build
  - yarn package

deploy:
  - provider: script
    script: yarn deploy
    on:
      branch: development


