AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Bootstrap Full Stack App consisting of a Vue App Deployed to S3 Bucket with CloudFront Distribution and a RESTful API Gateway with Lambda functions

Resources:
  VueApp:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./packages/vue-app/ui.yaml
      Parameters:
        Param1: hello
        Param2: world

  RestfulAPI:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./packages/api/api.yaml
      Parameters:
        Param1: hola
        Param2: mundo
  
