AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swagger specified inline and backed by a Lambda function

Resources:
  UserPostsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
        StageName: prod
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/posts":
                get:
                  summary: List all Posts by all users
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListPosts.Arn}/invocations
                  responses: {}
                post:
                  summary: Create a User Post
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreatePost.Arn}/invocations
                  responses: {}
              "/posts/{postId}":
                get:
                  summary: Show Post by Post Id
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ShowPostById.Arn}/invocations
                  responses: {}
  # 
  # API definitions
  # 
  ListPosts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list.handler
      Runtime: nodejs8.10
      CodeUri: ./dist/posts
      Events:
        ListPostsApi:
          Type: Api
          Properties:
            Path: /posts
            Method: GET
            RestApiId: !Ref UserPostsApiGateway

  CreatePost:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handler
      Runtime: nodejs8.10
      CodeUri: ./dist/posts
      Events:
        CreatePostApi:
          Type: Api
          Properties:
            Path: /posts
            Method: POST
            RestApiId: !Ref UserPostsApiGateway
            
  ShowPostById:
    Type: AWS::Serverless::Function
    Properties:
      Handler: byId.handler
      Runtime: nodejs8.10
      CodeUri: ./dist/posts
      Events:
        CreatePostApi:
          Type: Api
          Properties:
            Path: /posts/{postId}
            Method: GET
            RestApiId: !Ref UserPostsApiGateway

Outputs:

  ApiURL:
    Description: "API endpoint URL"
    Value: !Sub "https://${UserPostsApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"