openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Crud App
  license:
    name: MIT
servers:
  - url: http://poststore.swagger.io/v1
paths:
  /posts:
    get:
      summary: List all posts
      operationId: listPosts
      tags:
        - posts
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 10)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of posts
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Posts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a post
      operationId: createPosts
      tags:
        - posts
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /posts/{postId}:
    get:
      summary: Info for a specific post
      operationId: showPostById
      tags:
        - posts
      parameters:
        - name: postId
          in: path
          required: true
          description: The id of the post to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Posts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Post:
      required:
        - id
        - userId
        - title
        - body
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Posts:
      type: array
      items:
        $ref: "#/components/schemas/Post"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
